version: '3'
services:
  webapp:
    image: webapp
    restart: unless-stopped
    container_name: caloman
    ports:
      - "8080:8080"
    build:
      context: ./
    environment:
      - CALORIES_MANAGER_ROOT=/usr/local/tomcat/caloman
    volumes:
      - ./:/usr/local/tomcat/caloman
